name = "buzzu-reputation"
account_id = "8a6aa46bac19e8cc88a102ba96b5ade0"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-11"

[durable_objects]
bindings = [
  { name = "REPUTATION_BUCKET", class_name = "ReputationBucket" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReputationBucket"]
